### ISSUE TITLE
No uppercase or small capitals in subscript

### ISSUE THREAD

**Issue by mpercillier** [alif-type/libertinus#282]
Characters that are uppercase or small caps do not appear in subscript. For example, `eat\textsubscript{INF}`{.latex} appears as "eatINF" rather than "eat<sub>INF</sub>".

MWE below:
```{.latex}
%!TEX TS-program = xelatex
%!TEX encoding = UTF-8 Unicode

\documentclass[12pt]{article}
\usepackage{geometry}
\geometry{letterpaper}
\usepackage{graphicx}
\usepackage{amssymb}

\usepackage{fontspec,xltxtra,xunicode}
\defaultfontfeatures{Mapping=tex-text}
\setromanfont[Mapping=tex-text]{Libertinus Serif}
\setsansfont[Scale=MatchLowercase,Mapping=tex-text]{Gill Sans}
\setmonofont[Scale=MatchLowercase]{Andale Mono}

\title{Brief Article}
\author{The Author}

\begin{document}
\maketitle

This is a test.

This is a test with subscript\textsubscript{here}.

Subscripts with capitals\textsubscript{HERE}.

Let's test \textsc{Small Caps}.

Small caps in subscript\textsubscript{\textsc{test}}.

Test a mix of uppercase and lowercase letters in the subscript\textsubscript{camelCase}.

\end{document}  
```

![libertinus-subscript-issue](https://user-images.githubusercontent.com/14906564/65431038-205c9d80-de19-11e9-93d9-ed07291ec4f1.png)

**Comment by sieversMartin** [comment]
Am 23.09.19 um 15:46 schrieb mpercillier:
> Characters that are uppercase or small caps do not appear in subscript.
> For example, |eat\textsubscript{INF}|{.latex} appears as "eatINF" rather
> than "eat_INF ".

Using the libertinus-otf package rather than loading the font directly
(which btw does not work for me with TeX Live 2019 due to the spaces
within the font name), I get everything correct:

\documentclass[12pt]{article}
\usepackage{geometry}
\geometry{letterpaper}
\usepackage{graphicx}
\usepackage{amssymb}

\usepackage{fontspec,xltxtra,xunicode}
\defaultfontfeatures{Mapping=tex-text}
%\setromanfont[Mapping=tex-text]{"Libertinus Serif"}
\usepackage{libertinus-otf}
%\setsansfont[Scale=MatchLowercase,Mapping=tex-text]{Gill Sans}
%\setmonofont[Scale=MatchLowercase]{Andale Mono}

\title{Brief Article}
\author{The Author}

\begin{document}
\maketitle

This is a test.

This is a test with subscript\textsubscript{here}.

Subscripts with capitals\textsubscript{HERE}.

Let's test \textsc{Small Caps}.

Small caps in subscript\textsubscript{\textsc{test}}.

Test a mix of uppercase and lowercase letters in the
subscript\textsubscript{camelCase}.

\end{document}


-- 

Martin Sievers -- Einfach schöner publizieren

Im Alten Garten 5
54296 Trier

Telefon:  +49 (0) 651 4936567-0
Telefax:  +49 (0) 651 4936567-9
Mobil:    +49 (0) 179 7347726

Internet: http://www.schoenerpublizieren.de
E-Mail:   info@schoenerpublizieren.de

**Comment by mpercillier** [comment]
I tried your suggestion but I got the exact same output as before. Then I also commented out the lines `\usepackage{fontspec,xltxtra,xunicode}` and `\defaultfontfeatures{Mapping=tex-text}` and now it works. Thanks a lot! It would be interesting to know what causes this difference in behaviour.

**Comment by sieversMartin** [comment]
Am 23.09.19 um 17:06 schrieb mpercillier:
> I tried your suggestion but I got the exact same output as before. Then
> I also commented out the lines |\usepackage{fontspec,xltxtra,xunicode}|
> and |\defaultfontfeatures{Mapping=tex-text}| and now it works. Thanks a
> lot! It would be interesting to know what causes this difference in
> behaviour.

AFAIR xltxtra and xunicode are outdated and should not be used any
longer. In my first answer I did indeed overlook your initial problem.
Sorry for that. My XeLaTeX shows the same behaviour.

**Comment by khaledhosny** [comment]
The subscript/superscript features don’t cover all glyphs in the font, that would be huge undertaking. If you require arbitrary superscript or subscript characters then I suggest you don’t use these feature and instead use scaled down version of the font (you can play with embolden and letter spacing features to obtain some optical correction for the small sizes).

**Comment by khaledhosny** [comment]
Something like (adjust the `FakeBold` and `FakeStretch` values to your liking:
```tex
\documentclass[12pt]{article}

\usepackage{fontspec}
\setmainfont[
  SizeFeatures = {
    {Size=-12, FakeBold=1.5, FakeStretch=1.1},
    {Size=12-},
  }
]{Libertinus Serif}
\setsansfont[Scale=MatchLowercase]{Gill Sans}
\setmonofont[Scale=MatchLowercase]{Andale Mono}

\title{Brief Article}
\author{The Author}

\begin{document}
\maketitle

This is a test.

This is a test with subscript\textsubscript{here}.

Subscripts with capitals\textsubscript{HERE}.

Let's test \textsc{Small Caps}.

Small caps in subscript\textsubscript{\textsc{test}}.

Test a mix of uppercase and lowercase letters in the subscript\textsubscript{camelCase}.

\end{document}
```

![result](https://user-images.githubusercontent.com/93914/65458317-9f6bc900-de4d-11e9-96a4-6deef518ee58.png)
