### ISSUE TITLE
Build faills if `python` binary is Python 2

### ISSUE THREAD

**Issue by waldyrious** [alif-type/libertinus#306]
On macOS, the default `python` binary is Python 2. Because of this, running `make` results in the following error:

```
❯ make
      BUILD  LibertinusSans-Regular
  File "tools/build.py", line 44
SyntaxError: Non-ASCII character '\xc2' in file tools/build.py on line 44, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
make: *** [build/LibertinusSans-Regular.otl.otf] Error 1
```

I fixed this by changing `Makefile` like this:

```diff
 SOURCEDIR=sources
 BUILDDIR=build
 GSUB=$(SOURCEDIR)/features/gsub.fea
 DOC=documentation
 TOOLS=tools
 
-PY?=python
+PY?=python3
 BUILD=$(TOOLS)/build.py
 NORMALIZE=$(TOOLS)/sfdnormalize.py
```

But ideally the Makefile should work out of the box. [IIUC](https://www.python.org/dev/peps/pep-0394/) it should be safe to expect the `python3` binary to be available if Python 3 is installed, so perhaps the change above could be committed to the Makefile. WDYT?

**Comment by khaledhosny** [comment]
Makes sense (IIRC, on Windows there is no versioned Python binary, but I don’t think this make file is usable on Windows anyway). BTW, I always use `venv` so the `python` binary is a symlink to the version used for building the virtual environment.

**Comment by alerque** [comment]
Ay, this change breaks some distros that don't have a python3 executable. The reason this variable was assigned with `?=` is so it could be set at runtime: `make PY=python3 <target>`. Defaulting to `python` is generally the best bet these days. If you wanted to get fancy I think you'd need to use a combination of `which` and `command` or `hash` to figure out _if_ there was a `python3`, then check for `python`. Frankly given the number of different ways Python could be installed I generally think it's best to just assume `python` and let the user specify otherwise for cases where that's different.

**Comment by waldyrious** [comment]
> If you wanted to get fancy I think you'd need to use a combination of `which` and `command` or `hash` to figure out if there was a `python3`, then check for `python`. 

I suppose it would be possible to perform a simple version check using the `python` binary and throw an appropriate error if it's not v3, right?

Or maybe even better, is there a possibility that `tools/build.py` could be made backward compatible so that it works both on Python 3 and Python 2? (the issue where it fails seems to be merely a matter of specifying the encoding, but there could be further errors down the road).

**Comment by khaledhosny** [comment]
No need to make things complex, `python3` binary should present on most systems, and of the odd one that does not have it building with `make PY=python` should do it. We require Python 3 (3.6+ actually, but lets keep things simple), so it makes sense to be explicit about this since in majority of systems `python` binary is Python 2. I have no intention to support Python 2.

**Comment by alerque** [comment]
I guess I'm a bit meaner. Python 2 has been EOL and is not even receiving security fixes at this point. Anybody with a system that defaults to it has bigger problems in my mind. On the other hand `python3` as a bin name seems a little more widespread than I thought (it's usually just a symlink not actually the binary, but whatever).
